#ifndef EXPORT_HPP
#define EXPORT_HPP

#include <QxOrm.h>

#ifdef _BUILD_MY_DEMO

#define QX_MY_DEMO_EXPORT QX_DLL_EXPORT_HELPER
#define QX_REGISTER_HPP_MY_DEMO  QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_MY_DEMO  QX_REGISTER_CPP_EXPORT_DLL

#else

#define QX_MY_DEMO_EXPORT QX_DLL_IMPORT_HELPER
#define QX_REGISTER_HPP_MY_DEMO  QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_MY_DEMO  QX_REGISTER_CPP_IMPORT_DLL

#endif

#endif // EXPORT_HPP